### ISSUE TITLE
Spurious `convert` exported.

### ISSUE THREAD

**Issue by KristofferC** [tanmaykm/OpenAPIClient.jl#2]
https://github.com/tanmaykm/OpenAPIClient.jl/blob/d953ec544f00c4f72f77dfbadbd8cbef0db0fa91/test/petstore_v3/petstore/src/PetStoreClient.jl#L18-L27

Comes from expanding 

```
# export models
{{#models}}
export convert{{#model}}, {{classname}}{{/model}}
{{/models}}

# export operations
{{#apiInfo}}
export convert{{#apis}}, {{classname}}{{/apis}}
{{/apiInfo}}
```

in `client.mustache`. I guess this `model` and `apis` key does not exist.

**Comment by tanmaykm** [comment]
fixed via https://github.com/OpenAPITools/openapi-generator/commit/3bb90d6b500540aa5d305a77a2cf033e649aecb7
