### ISSUE TITLE
Experiences from trying to generate a client from GitHub

### ISSUE THREAD

**Issue by KristofferC** [tanmaykm/OpenAPIClient.jl#3]
Command to generate it:

```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \
   -i https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.yaml \
   -g julia \
   -o ~/GitHubClient
```

## Some files missing:

```jl
julia> include("src/APIClient.jl")
[ Info: Precompiling OpenAPIClient [12741cc8-1e73-42f3-a27c-379dbea8d6a3]
ERROR: LoadError: SystemError: opening file "/Users/kristoffercarlsson/GitHubClient/src/model_ModelImport.jl": No such file or directory
```

There is however a file called `model_Import` that contains the `ModelImport` type.

## Invalid field names

```julia
mutable struct ReactionRollup <: OpenAPIClient.APIModel
    url::Any # spec type: Union{ Nothing, URI } # spec name: url
    total_count::Any # spec type: Union{ Nothing, Int32 } # spec name: total_count
    1::Any # spec type: Union{ Nothing, Int32 } # spec name: +1
    _1::Any # spec type: Union{ Nothing, Int32 } # spec name: -1
```

The `1` is invalid. The `var"1"` syntax could be used.

The spec shows this type as:

```
        total_count:
          type: integer
        "+1":
          type: integer
        "-1":
```

So the `-` has turned to `_` and the plus has dissapeared.

## Invalid function names

```julia
function _oacinternal_actions/addCustomLabelsToSelfHostedRunnerForOrg
...
```

Function name contains `/`.

**Comment by tanmaykm** [comment]
> Function name contains /.

should be handled now with https://github.com/OpenAPITools/openapi-generator/commit/091bf3c6be809226866f2f9acade2186900ec209

**Comment by tanmaykm** [comment]
These should now be handled with https://github.com/tanmaykm/OpenAPIClient.jl/pull/6 and https://github.com/tanmaykm/openapi-generator/releases/tag/juliacodegenv2
