### ISSUE TITLE
Use `var""` syntax instead of escaping etc?

### ISSUE THREAD

**Issue by KristofferC** [tanmaykm/OpenAPIClient.jl#5]
It is possible to have arbitrarily named identifiers with the `var""` syntax:

```julia
julia> var"function"  = 3
3

julia> var"function"
3
```

It might be interesting to think about using that for identifiers that cannot be represented directly in Julia instead of doing all the escaping and removal of them.

Some transformations should probably be done so that `var""` is not required in most cases but it might be easier for users if they don't have to learn all the escaping rules and can just use the actual name.

**Comment by tanmaykm** [comment]
done in https://github.com/tanmaykm/OpenAPIClient.jl/pull/6
